### ISSUE TITLE
uplaod.html 404

### ISSUE THREAD

**Issue by YouZhengChuan** [DDHax/sis#1]
`get /uplaod.html` or `get /upload.html` reponse is 404 not found.

**Comment by DDHax** [comment]
抱歉，sis本身并没有提供任何交互界面。
这个网页文件不能从sis服务程序get出来，但你可以编辑修改该文件的post地址，然后直接用浏览器本地打开测试上传功能

**Comment by DDHax** [comment]
1.0.1版本提供了一个在线版本交互界面
