### ISSUE TITLE
如何在server上分享图片链接呢？

### ISSUE THREAD

**Issue by Aquarian-Age** [DDHax/sis#2]
安装好了　服务器以ｓｅｒｖｅｒ启动后本地测试上传成功
发现不知道怎么在服务端把上传的图片分享出来
简单说就是图片链接不知道怎么弄成　http://example.tk/xxxx.png 之类的
这个现在可以实现吗？

**Comment by DDHax** [comment]
图片上传成功之后会返回一个访问地址，可以直接使用该地址分享。
